# This workflow runs PHPStan security analysis tool
# PHPStan uses `phpstan.neon` configuration file.
# The results are shown under the `Execute PHPStan` in the specific GitHub Action
# More information: https://github.com/phpstan/phpstan

name: PHPStan Security Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  phpstan-security-scan:
    name: PHPStan Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          ini-values: "memory_limit=-1"
      - name: Download deps
        run: composer update --no-interaction --no-progress
      - name: Download PHPStan
        run: composer require --dev phpstan/phpstan
      - name: Download Larastan v1
        # Larastan adds static typing to Laravel framework
        # Larastan v1 is intended for Laraval < 9. For Laraval >= 9 use v2
        run: composer require nunomaduro/larastan:^1.0 --dev
      - name: Download mcrypt helper
        # Download mcrypt stub to cover mcrypt functions
        run: wget https://raw.githubusercontent.com/JetBrains/phpstorm-stubs/master/mcrypt/mcrypt.php -O _mcrypt_helper.php
      - name: Execute PHPStan
        # Run the PHPStan tool for the whole directory ('.'), excluded directories are in the phpstan.neon conf file
        # along with the `rule level (-l)`. More information: https://phpstan.org/user-guide/rule-levels
        run: vendor/bin/phpstan analyze . --no-progress --error-format=github -c phpstan.neon
        env:
          # Example 32 bytes key to avoid `No application encryption key has been specified` error
          APP_KEY: APP_KEY_CREATED_FOR_PHPSTAN_TEST
