# This workflow checks out code and performs a Psalm analysis.
# This workflow is divided into two jobs.
# First, the basic scan - due to the verbosity, the results are shown under the `Execute Psalm`
# in the specific GitHub Action.
# The second one - Taint Analysis - tries to find connections between user-controlled input
# and places that are not user-controlled. The results from the taint analysis are integrated
# with the GitHub Advanced Security Dashboard.
# Both jobs use the `psalm.xml` configuration file.
# More information: https://github.com/vimeo/psalm

name: Psalm Security Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
permissions:
  contents: read
  security-events: write
    
jobs:
  psalm-security-scan-basic:
    name: Psalm Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          ini-values: "memory_limit=-1"
          extensions: mbstring, intl
      - name: Download deps
        run: composer update --no-interaction --no-progress
      - name: Install laravel-ide-helper
        run: composer require --dev barryvdh/laravel-ide-helper
      - name: Download Psalm
        run: composer require --dev vimeo/psalm
      - name: PHPDoc generation for Laravel Facades
        run: php artisan ide-helper:generate
      - name: Download mcrypt helper
        run: wget https://raw.githubusercontent.com/JetBrains/phpstorm-stubs/master/mcrypt/mcrypt.php -O _mcrypt_helper.php
      - name: Execute Psalm
        run: ./vendor/bin/psalm --long-progress --no-cache --report=results_base.sarif
      # Upload findings to GitHub Advanced Security Dashboard - disabled for 'base' scan due to verbosity
      # - name: Upload SARIF file for GitHub Advanced Security Dashboard
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: results_base.sarif
      #   if: always()

  psalm-security-scan-taint-analysis:
    name: Psalm Security Scan (Taint Analysis)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          ini-values: "memory_limit=-1"
          extensions: mbstring, intl
      - name: Download deps
        run: composer update --no-interaction --no-progress
      - name: Install laravel-ide-helper
        run: composer require --dev barryvdh/laravel-ide-helper
      - name: Download Psalm
        run: composer require --dev vimeo/psalm
      - name: Download mcrypt helper
        run: wget https://raw.githubusercontent.com/JetBrains/phpstorm-stubs/master/mcrypt/mcrypt.php -O _mcrypt_helper.php
      - name: PHPDoc generation for Laravel Facades
        run: php artisan ide-helper:generate
      - name: Execute Psalm (Taint Analysis)
        run: ./vendor/bin/psalm --long-progress --taint-analysis --report=results_taint.sarif
      # Upload findings to GitHub Advanced Security Dashboard
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results_taint.sarif
        if: always()
