name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      #  contents: write # only for delete-branch option
      issues: write
      #  pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          debug-only: true
          ascending: true
          operations-per-run: 1000 # just while we're debugging
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          exempt-all-milestones: true
          stale-issue-message: >
            Is this still relevant? We haven't heard from anyone in a bit. If so,
            please comment with any updates or additional detail.
            
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Don't
            take it personally, we just need to keep a handle on things. Thank you
            for your contributions!
          close-issue-message: >
            This issue has been automatically closed because it has not had
            recent activity. If you believe this is still an issue, please confirm that
            this issue is still happening in the most recent version of Snipe-IT and reply
            to this thread to re-open it.
          # There doesn't seem to be a 'reopen issue message'?
          # Since there is no 'stale-pr-message' - PR's should not be stale'd
          stale-issue-label: stale
          exempt-issue-labels: >
            pinned,security,:woman_technologist: ready for dev,:moneybag: bounty,:hand: bug,ğŸ” security,ğŸ‘©â€ğŸ’» ready for dev,ğŸ’° bounty,âœ‹ bug